# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler/blob/master/README.md

name: Labeler
on:
  schedule:
    - cron: '*/30 * * * *' # Every 1st and 30th minute

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
    - uses: paulfantom/periodic-labeler@v0.0.1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        GITHUB_REPOSITORY: ${{ github.repository }}
        LABEL_MAPPINGS_FILE: .github/labeler.yml
